### ISSUE TITLE
Generating screenshots for ios store

### ISSUE THREAD

**Issue by morenoh149** [hypery2k/cordova-media-generator#7]
I'm trying to submit my ios app to the appstore.
It needs a 1242 x 2208 image.
it needs an image for 4.7 inch, 5.5 inch, 4 inch, 3.5 inch and ipad.

Could this tool generate these? if this doesn't exist I'd like to help make this tool for other cordova devs.

**Comment by morenoh149** [comment]
nvm the sim `cmd + S` does save to the right dimensions.

**Comment by hypery2k** [comment]
maybe we can add a hook for the screenshot creation
